{
 "title": "Vector",
 "description": "Vector.dev Kubernetes cluster monitoring dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(service) (vector_uptime_seconds)"
    }
   ]
  },
  {
   "title": "Input events count (events/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (component_id) (rate(vector_component_received_events_total{component_kind=\"source\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input events bytes rate (bytes/sec)",
   "type": "timeseries",
   "description": "The rate of bytes processed by the component.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (component_id) (rate(vector_component_received_event_bytes_total{component_kind=\"source\"}[1m]))",
     "legendFormat": "{{ component_id }}"
    }
   ]
  },
  {
   "title": "Transform events count (events/sec)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (component_id) (rate(vector_component_received_events_total{component_kind=\"transform\"}[1m]))",
     "legendFormat": "{{ component_name }}"
    }
   ]
  },
  {
   "title": "Transform events bytes rate (bytes/sec)",
   "type": "timeseries",
   "description": "The rate of bytes processed by the component.",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (component_id) (rate(vector_component_received_event_bytes_total{component_kind=\"transform\"}[1m]))",
     "legendFormat": "{{ component_id }}"
    }
   ]
  },
  {
   "title": "Transform utilization",
   "type": "timeseries",
   "description": "A ratio from 0 to 1 of the load on a component. A value of 0 would indicate a completely idle component that is simply waiting for input. A value of 1 would indicate a that is never idle. This value is updated every 5 seconds.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (component_id) (vector_utilization{component_kind=\"transform\"})",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Output events bytes count (events/sec)",
   "type": "timeseries",
   "description": "The count of bytes processed by the component.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (component_id) (rate(vector_component_received_events_total{component_kind=\"sink\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output events count (events/sec)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (component_id) (rate(vector_component_received_events_total{component_kind=\"sink\"}[1m]))",
     "legendFormat": "{{ component_name }}"
    }
   ]
  },
  {
   "title": "Output events bytes rate (bytes/sec)",
   "type": "timeseries",
   "description": "The rate of bytes processed by the component.",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (component_id) (rate(vector_component_received_event_bytes_total{component_kind=\"sink\"}[1m]))",
     "legendFormat": "{{ component_id }}"
    }
   ]
  },
  {
   "title": "Output utilization",
   "type": "timeseries",
   "description": "A ratio from 0 to 1 of the load on a component. A value of 0 would indicate a completely idle component that is simply waiting for input. A value of 1 would indicate a that is never idle. This value is updated every 5 seconds.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (component_id) (vector_utilization{component_kind=\"sink\"})",
     "legendFormat": "{{component_id}}"
    }
   ]
  }
 ]
}